// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzRygizV3t40e9Lr3SthHqQTy0WpGggps',
    appId: '1:494745694096:web:ac1cc2ab406e7dea3b4d15',
    messagingSenderId: '494745694096',
    projectId: 'expense-tracker-d18df',
    authDomain: 'expense-tracker-d18df.firebaseapp.com',
    storageBucket: 'expense-tracker-d18df.firebasestorage.app',
    measurementId: 'G-0648RCHD2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6PO6Jen8K7YSHclinTBHKBH-eei0ttcQ',
    appId: '1:494745694096:android:781221c8bc3a2dcc3b4d15',
    messagingSenderId: '494745694096',
    projectId: 'expense-tracker-d18df',
    storageBucket: 'expense-tracker-d18df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKDQ1mXsK08nQS53zD1NII-BtoTxdOv58',
    appId: '1:494745694096:ios:e387cfdf1fb57d1d3b4d15',
    messagingSenderId: '494745694096',
    projectId: 'expense-tracker-d18df',
    storageBucket: 'expense-tracker-d18df.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKDQ1mXsK08nQS53zD1NII-BtoTxdOv58',
    appId: '1:494745694096:ios:e387cfdf1fb57d1d3b4d15',
    messagingSenderId: '494745694096',
    projectId: 'expense-tracker-d18df',
    storageBucket: 'expense-tracker-d18df.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzRygizV3t40e9Lr3SthHqQTy0WpGggps',
    appId: '1:494745694096:web:2de104b92e9c69183b4d15',
    messagingSenderId: '494745694096',
    projectId: 'expense-tracker-d18df',
    authDomain: 'expense-tracker-d18df.firebaseapp.com',
    storageBucket: 'expense-tracker-d18df.firebasestorage.app',
    measurementId: 'G-LDJD9BE5JH',
  );
}
